source 'https://rubygems.org'

gem 'activerecord', '6.1.7.1', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
gem 'sinatra'
gem 'thin'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'bcrypt'
gem 'rake'
gem 'rack-flash3'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
gem 'capybara'
gem 'rerun', '~> 0.13.0'
gem 'require_all'
gem 'wdm'
